### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by kroggen** [vladimirfedorov/sqlite3-wrapper#1]
Hi Vladimir!

How are you there in Russia? I am from Brazil.

Thank you for sharing this work. It is really useful.

I have some suggestions.

One of them is to change the order of the arguments in the update function to a more intuitive way, and to allow optional arguments.

Another one is to convert the value to a JSON string if it is an object or array, so it can be saved in the database. I am working on a way to retrieve these values already parsed from the database. There are currently 2 ways of doing it.

Indeed I forked your repo and I am making changes to it. I invite you to check the changes and if you like them I can make a pull request to your master branch.

I made some corrections too.

What do you think about them?

I hope you like.

Cheers!

**Comment by vladimirfedorov** [comment]
Hi kroggen! Thanks for your interest, I am really happy you found this useful, and your fix to convertValue definitely must be there. Not sure about the order of arguments, as there are some projects that use this library and this update will break them (and it is hard to see the difference between the original and the proposed function).

**Comment by kroggen** [comment]
Thank you for your response. It's good that you liked it.

Did you check each commit that I added? Note the "optional arguments in db.update()".

I know that some applications may be using it, but if these changes are useful it's better to do it now when there are not so many ones using it than later. Because I plan to spread/publicize it together with some changes in node-sqlite3 that does the opposite of convertvalue.

How many applications do you think are using it now? We must check if we can do it without causing much trouble. The npm site does not cite any application having it as dependency.

If this change is implemented in the master, we must put some information about the update in the README.

Or not implementing it... or using another funcion name... but the "update" is the best one.

What do you think?

**Comment by kroggen** [comment]
In some cases we will use the db.update without the where clause:

```javascript
db.update('users', {counter: 0}, function(error, changes) {
    // ...
})
```
or even without the callback:
```javascript
db.update('users', {counter: 0})
```
or with the where clause and without the callback:
```javascript
db.update('users', {active: false}, {id: user.id})
```

**Comment by vladimirfedorov** [comment]
I am strongly against changing parameters order - there are a lot of downloads of the library and hardly there can be anything worse than changing it in a way that can silently and without any warning corrupt user data - in a use case similar to your last example it will set the same id to all inactive users. Callbacks are optional in all functions. I may be better to keep your fork and extend the library with your own functions.

**Comment by kroggen** [comment]
OK Vladimir.
We can continue on other topics together.
Feel free to use the other functionality that I added, like convertValue.
