### ISSUE TITLE
Insert many values at the moment

### ISSUE THREAD

**Issue by xamgore** [vladimirfedorov/sqlite3-wrapper#3]
Hi there!

It is a common problem, when you need to send many data to a database using the only one request (to reduce the overhead time). It can be implemented by [passing records](https://github.com/vladimirfedorov/sqlite3-wrapper/blob/master/index.js#L97) to `VALUES (rec1), (rec2), …`, though it'll take too much time for me to test and send a pull request. So, if you (or me) will have a free time, think about it!

Thank you for your work!

**Comment by vladimirfedorov** [comment]
not an issue; multiple records for insert statement is a good idea for the next version.
